name: CI-FLUTTER-ANDROID
on:
  push:
    branches: [main, dev, test]
    paths: [frontend/**]
  pull_request:
    branches: [main, dev, test]
    paths: [frontend/**]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approved:
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

  flutter-frontend:
    name: Flutter (frontend) flutter-application and flutter-application-android #https://github.com/marketplace/actions/flutter-action
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          #flutter-version: 3.19.0
          flutter-version-file: frontend/smart_schedule/pubspec.yaml
      #Apply a patch|Sometimes you find a bug in Flutter and you fix it yourself (you're a rockstar!), and then submit a patch/PR to Flutter repository. However, everyone knows that code review takes time, but your app needs the fix now.
      #Ce pula mea o mai inseamna si asta
      - name: Apply temporary flutter patch
        run: | 
          set -e -u -x -o pipefail
          flutter --version
          SDK_DIR="${FLUTTER_HOME:-$FLUTTER_ROOT}"
          cd "$SDK_DIR"
          curl https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/137874.patch | git apply -v
          git status

      - name: Build flutter
        run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
        #run: flutter test INCA NU AVEM TESTELE

  android-build:
    needs: flutter-frontend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: frontend } }
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Set up Flutter for Android
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          #flutter-version: 3.24.0
          flutter-version-file: frontend/smart_schedule/pubspec.yaml
      - run: flutter pub get
      #- run: flutter test 
      - run: flutter build apk 
      - run: flutter build appbundle 