name: CI-FLUTTER-IOS
on:
  push:
    branches: [main, dev, test]
  pull_request:
    branches: [main, dev, test]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approved:
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
  flutter-fronted-iOS: #https://github.com/marketplace/actions/flutter-build-ios
    main:
      runs-on: macos-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter for iOs
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version-file: pubspec.yaml
        - run: flutter pub get
        - run: flutter test --if-present
        - run: flutter build ios --release --no-codesign