name: CI-FLUTTER-IOS
on:
  push:
    branches: [main, dev, test]
    paths: [frontend/**]
  pull_request:
    branches: [main, dev, test]
    paths: [frontend/**]
    types: [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approved:
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

  flutter-fronted-iOS: #https://github.com/marketplace/actions/flutter-build-ios
    name: Flutter-iOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Set up Flutter for iOs
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: frontend/smart_schedule/pubspec.yaml
      - run: flutter pub get
      - run: flutter test || true
      - run: flutter build ios --release --no-codesign