name: CI-NODE
on:
  push:
    branches: [main, dev, test]
    paths:
      - "backend/**"
      - ".github/workflows/ci-node.yml"
  pull_request:
    branches: [main, dev, test]
    paths:
      - "backend/**"
      - ".github/workflows/ci-node.yml"
    types: [opened, reopened, synchronize, labeled, unlabeled]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approved:
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

  node-backend:
    name: Node (backend) #https://github.com/actions/setup-node | https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v5 #https://github.com/actions/checkout
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        check-latest: false #verifica ultima versiune de node.js
        package-manager-cache: true #controleaza caching-ul automat pentru npm
        #registry-url: '' !!!SA REVIN SA SETEZ .npmrc sau .yarnrc
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm ci --ignore-scripts
    - run: npm run typecheck
    - run: npm run lint
    - run: npm test || true
    - run: npm run build